### ISSUE TITLE
AssertionError: Checkpoint detectron2://ImageNetPretrained/MSRA/R-50.pkl not found!

### ISSUE THREAD

**Issue by e96031413** [Majiker/BalancedMetaSoftmax-InstanceSeg#3] opened 2021-01-15 07:56 UTC
Thanks for your great work, after installing detectron2, I use the command to train the model
```
python ./projects/BALMS/train_net.py  --config-file ./projects/BALMS/configs/feature/sigmoid_resampling_mask_rcnn_R_50_FPN_1x.yaml --num-gpus 4
```
However, I encounter an unexpected error so that I cannot train the model
```
AssertionError: Checkpoint detectron2://ImageNetPretrained/MSRA/R-50.pkl not found!
```
I finally solved the problem by replacing [detectron2/engine/defaults.py Line 314](https://github.com/Majiker/BalancedMetaSoftmax-InstanceSeg/blob/main/detectron2/engine/defaults.py#L314) with the following code and then I can train now:
```
checkpoint =self.checkpointer.resume_or_load("/root/notebooks/nfs/work/yanwei.liu/BalancedMetaSoftmax-InstanceSeg/pretrains/R-50.pkl", resume=resume)
```
My question is that can we avoid this problem by modifying the source code?
or I can just change the path manually?

## Environment:

```
sys.platform            linux
Python                  3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) [GCC 7.3.0]
numpy                   1.19.5
detectron2              0.2.1 @/root/notebooks/nfs/work/yanwei.liu/BalancedMetaSoftmax-InstanceSeg/detectron2
Compiler                GCC 5.4
CUDA compiler           CUDA 10.0
detectron2 arch flags   7.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.1+cu92 @/opt/conda/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3             Tesla V100-PCIE-32GB (arch=7.0)
CUDA_HOME               /usr/local/cuda
Pillow                  8.1.0
torchvision             0.8.2+cu92 @/opt/conda/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0
fvcore                  0.1.2.post20210115
cv2                     4.1.2
----------------------  -------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 9.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
```

**Comment by jiawei-ren** [comment] 2021-01-19 08:52
The issue could be related to your installation or environment setup. 

As indicated in our commit history, we initialized the repository with the official detectron2 at [`commit d2b028a`](https://github.com/facebookresearch/detectron2/tree/d2b028ac3a80ccf6e7bb37acc0229b23c04125c0), and only made our changes in the third-party projects folder `projects/BALMS`. That means the code for loading checkpoints/pre-trained models, for example,  `detectron2/engine/defaults.py` as you have mentioned, is from the original detectron2. Since detectron2 has been well tested and we cannot reproduce this issue, we may only assume that the issue is related to your installation or environment setup, e.g. network issues, storage issues, etc.

For a detailed installation guide, please kindly refer to [issue#1](https://github.com/Majiker/BalancedMetaSoftmax-InstanceSeg/issues/1). We will add the installation description into the readme file for better clarification. Thank you for this detailed issue description and your pull request!

**Comment by jiawei-ren** [comment] 2021-01-28 14:55
I will close the issue for now. Feel free to reopen it if you have any further questions.

**Closed as completed by jiawei-ren** 2021-01-28 14:55 UTC

**Comment by JosephKJ** [comment] 2021-02-14 07:05
This is because of an update that happened in fvcore. 

Using this version helped me resolve the issue:

```
pip install fvcore==0.1.1.dev200512
```

**Comment by Zed-Yuan** [comment] 2022-09-29 11:01
Hi, I got a problem with the checkpoint, an error always occurs as 
AssertionError: Checkpoint ./output/t1/model_final.pth not found!
could u please help with that?

**Comment by XuHu0529** [comment] 2023-01-13 10:12
@Zed-Yuan Hi! I had the same error. Do you know how to solve it?
Thanks a lot?
